migration66

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -17,9 +17,9 @@ commands:
           when: on_fail
           command: |
             echo "Destroying environment: <<parameters.workflow_id>> "
-            aws cloudformation delete-stack --stack-name udapeople-backend-<<parameters.workflow_id>>
-            aws s3 rm s3://udapeople-<<parameters.workflow_id>> --recursive
-            aws cloudformation delete-stack --stack-name udapeople-frontend-<<parameters.workflow_id>>
+            aws cloudformation delete-stack --stack-name udacitypro3-backend-<<parameters.workflow_id>>
+            aws s3 rm s3://udacitypro3-<<parameters.workflow_id>> --recursive
+            aws cloudformation delete-stack --stack-name udacitypro3-frontend-<<parameters.workflow_id>>
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
     parameters:
@@ -267,174 +267,174 @@ jobs:
       - destroy_environment
       - revert-migrations    
 
-  # deploy-frontend:
-  #   docker:
-  #     - image: cimg/python:3.11.0-node  
-  #   steps:
-  #     - checkout
-  #     - install-awscli
-  #     - install-node
-  #     - restore_cache:
-  #         keys: [frontend-build]
-  #     - add_ssh_keys:
-  #         fingerprints: ["7b:24:6a:c4:2e:2e:d4:4b:52:49:0b:19:de:90:af:59"]
-  #     - run:
-  #         name: Install dependencies
-  #         command: |
-  #           cd frontend
-  #           npm install
-  #     - run:
-  #         name: Get backend url
-  #         command: |
-  #           BACKEND_AWS_PUBLIC_IP=$(aws ec2 describe-instances \
-  #             --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-  #             --query 'Reservations[*].Instances[*].PublicIpAddress' \
-  #             --output text)
-  #            API_URL="http://${BACKEND_AWS_PUBLIC_IP}:3030"
-  #            echo "API_URL=${API_URL}" >> frontend/.env
-  #            cat frontend/.env
-  #     - run:
-  #         name: Deploy frontend objects
-  #         command: |
-  #           cd frontend
-  #           npm install
-  #           npm run build
-  #           aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
-  #     - destroy_environment      
+  deploy-frontend:
+    docker:
+      - image: cimg/python:3.11.0-node  
+    steps:
+      - checkout
+      - install-awscli
+      - install-node
+      - restore_cache:
+          keys: [frontend-build]
+      - add_ssh_keys:
+          fingerprints: ["f1:6a:c1:70:98:df:97:93:2d:40:df:b9:f2:50:73:68"]
+      - run:
+          name: Install dependencies
+          command: |
+            cd frontend
+            npm install
+      - run:
+          name: Get backend url
+          command: |
+            BACKEND_AWS_PUBLIC_IP=$(aws ec2 describe-instances \
+              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --output text)
+             API_URL="http://${BACKEND_AWS_PUBLIC_IP}:3030"
+             echo "API_URL=${API_URL}" >> frontend/.env
+             cat frontend/.env
+      - run:
+          name: Deploy frontend objects
+          command: |
+            cd frontend
+            npm install
+            npm run build
+            aws s3 cp dist s3://udacitypro3-${CIRCLE_WORKFLOW_ID:0:7} --recursive
+      - destroy_environment      
                     
-  # deploy-backend:
-  #   docker:
-  #     - image: cimg/python:3.11.0-node  
-  #   steps:
-  #     - checkout
-  #     - install-awscli
-  #     - install_ansible
-  #     - restore_cache:
-  #         keys: [backend-build]
-  #     - attach_workspace:
-  #         at: ~/
-  #     - run:
-  #         name: install tsc
-  #         command: |
-  #          npm install typescript@latest -g
-  #          tsc --init
-  #          echo tsc --version
-  #     - add_ssh_keys:
-  #         fingerprints: ["7b:24:6a:c4:2e:2e:d4:4b:52:49:0b:19:de:90:af:59"] 
-  #     - run:
-  #         name: Package Backend
-  #         command: |
-  #           cd backend
-  #           npm run build
-  #           tar -czf artifact.tar.gz dist/* package*
-  #           cd ..
-  #           cp backend/artifact.tar.gz .circleci/ansible/roles/deploy/files
-  #     - run:
-  #         name: Deploy backend
-  #         command: |
-  #           cd .circleci/ansible
-  #           cat inventory.txt
-  #           ansible-playbook -i inventory.txt deploy-backend.yml
-  #     - destroy_environment  
-  #     - revert-migrations 
+  deploy-backend:
+    docker:
+      - image: cimg/python:3.11.0-node  
+    steps:
+      - checkout
+      - install-awscli
+      - install_ansible
+      - restore_cache:
+          keys: [backend-build]
+      - attach_workspace:
+          at: ~/
+      - run:
+          name: install tsc
+          command: |
+           npm install typescript@latest -g
+           tsc --init
+           echo tsc --version
+      - add_ssh_keys:
+          fingerprints: ["f1:6a:c1:70:98:df:97:93:2d:40:df:b9:f2:50:73:68"] 
+      - run:
+          name: Package Backend
+          command: |
+            cd backend
+            npm run build
+            tar -czf artifact.tar.gz dist/* package*
+            cd ..
+            cp backend/artifact.tar.gz .circleci/ansible/roles/deploy/files
+      - run:
+          name: Deploy backend
+          command: |
+            cd .circleci/ansible
+            cat inventory.txt
+            ansible-playbook -i inventory.txt deploy-backend.yml
+      - destroy_environment  
+      - revert-migrations 
 
-  # smoke-test:
-  #   docker:
-  #     - image: python:3.7-alpine3.11
-  #   steps:
-  #     - checkout
-  #     - attach_workspace:
-  #         at: ~/
-  #     - run:
-  #         name: Install dependencies
-  #         command: |
-  #           apk add --update curl
-  #           pip install awscli
-  #     - run:
-  #         name: Get backend url
-  #         command: |
-  #           BACKEND_AWS_PUBLIC_IP=$(aws ec2 describe-instances \
-  #             --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-  #             --query 'Reservations[*].Instances[*].PublicIpAddress' \
-  #             --output text)
-  #            API_URL="http://${BACKEND_AWS_PUBLIC_IP}:3030"
-  #            if curl "${API_URL}/api/status" | grep "ok"
-  #             then
-  #                 return 0
-  #             else
-  #                 return 1
-  #             fi
+  smoke-test:
+    docker:
+      - image: python:3.7-alpine3.11
+    steps:
+      - checkout
+      - attach_workspace:
+          at: ~/
+      - run:
+          name: Install dependencies
+          command: |
+            apk add --update curl
+            pip install awscli
+      - run:
+          name: Get backend url
+          command: |
+            BACKEND_AWS_PUBLIC_IP=$(aws ec2 describe-instances \
+              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --output text)
+             API_URL="http://${BACKEND_AWS_PUBLIC_IP}:3030"
+             if curl "${API_URL}/api/status" | grep "ok"
+              then
+                  return 0
+              else
+                  return 1
+              fi
           
-  #     - run:
-  #         name: Frontend smoke test.
-  #         command: |
-  #           URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com"             
-  #           echo ${URL} 
-  #           if curl -s ${URL} | grep "Welcome"
-  #           then
-  #             exit 0
-  #           else
-  #             exit 1
-  #           fi   
-  #     # Here's where you will add some code to rollback on failure  
+      - run:
+          name: Frontend smoke test.
+          command: |
+            URL="http://udacitypro3-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com"             
+            echo ${URL} 
+            if curl -s ${URL} | grep "Welcome"
+            then
+              exit 0
+            else
+              exit 1
+            fi   
+      # Here's where you will add some code to rollback on failure  
 
-  #     - destroy_environment  
-  #     - revert-migrations 
+      - destroy_environment  
+      - revert-migrations 
 
-  # cloudfront-update:
-  #   docker:
-  #     - image: cimg/python:3.11.0-node
-  #   steps:
-  #     - checkout
-  #     - install-awscli
-  #     - install_ansible
-  #     - run:
-  #         name: get old workflow ID
-  #         command: |
-  #           export OldWorkflowID=$(aws cloudformation \
-  #           list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
-  #           --no-paginate --output text)
-  #           echo ${OldWorkflowID}
-  #             curl https://kvdb.io/hw6KQtMQosxLJgUHxcCJY/OldWorkflowID -d "$OldWorkflowID"  
-  #     - run:
-  #         name: Updating cloudfront distribution
-  #         command: |
-  #           aws cloudformation deploy \
-  #           --template-file .circleci/files/cloudfront.yml \
-  #           --stack-name udapeople-cloudfront \
-  #           --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" 
-  #     # Here's where you will add some code to rollback on failure 
+  cloudfront-update:
+    docker:
+      - image: cimg/python:3.11.0-node
+    steps:
+      - checkout
+      - install-awscli
+      - install_ansible
+      - run:
+          name: get old workflow ID
+          command: |
+            export OldWorkflowID=$(aws cloudformation \
+            list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+            --no-paginate --output text)
+            echo ${OldWorkflowID}
+              curl https://kvdb.io/LGTr3fsCgrdqatmbnibNmN/OldWorkflowID -d "$OldWorkflowID"  
+      - run:
+          name: Updating cloudfront distribution
+          command: |
+            aws cloudformation deploy \
+            --template-file .circleci/files/cloudfront.yml \
+            --stack-name udapeople-cloudfront \
+            --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" 
+      # Here's where you will add some code to rollback on failure 
       
-  #     - destroy_environment
+      - destroy_environment
 
     
-  # cleanup:
-  #   docker:
-  #     - image: cimg/python:3.11.0-node
-  #   steps:
-  #       - checkout
-  #       - install-awscli
-  #       - install_ansible
-  #       - run:
-  #           name: Remove old stack workflow 
-  #           command: |
-  #             export OldWorkflowID=$(curl --insecure https://kvdb.io/hw6KQtMQosxLJgUHxcCJY/OldWorkflowID)
-  #             echo OldWorkflowID: "${OldWorkflowID}"
-  #             echo CIRCLE_WORKFLOW_ID "${CIRCLE_WORKFLOW_ID:0:7}"        
-  #             export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
-  #                     --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
-  #             echo Stack names: "${STACKS[@]}"  
+  cleanup:
+    docker:
+      - image: cimg/python:3.11.0-node
+    steps:
+        - checkout
+        - install-awscli
+        - install_ansible
+        - run:
+            name: Remove old stack workflow 
+            command: |
+              export OldWorkflowID=$(curl --insecure https://kvdb.io/LGTr3fsCgrdqatmbnibNmN/OldWorkflowID)
+              echo OldWorkflowID: "${OldWorkflowID}"
+              echo CIRCLE_WORKFLOW_ID "${CIRCLE_WORKFLOW_ID:0:7}"        
+              export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
+                      --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
+              echo Stack names: "${STACKS[@]}"  
 
-  #             if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
-  #             then
-  #               echo oldstack: "${s3://udapeople-${OldWorkflowID}}"  
-  #               aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
-  #               aws cloudformation delete-stack --stack-name "backend-${OldWorkflowID}"
-  #               aws cloudformation delete-stack --stack-name "frontend-${OldWorkflowID}"
-  #               echo "Stacks deleted succesfully"
-  #             else
-  #               echo nothing to delete
-  #             fi   
+              if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+              then
+                echo oldstack: "${s3://udapeople-${OldWorkflowID}}"  
+                aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
+                aws cloudformation delete-stack --stack-name "backend-${OldWorkflowID}"
+                aws cloudformation delete-stack --stack-name "frontend-${OldWorkflowID}"
+                echo "Stacks deleted succesfully"
+              else
+                echo nothing to delete
+              fi   
               
 
 workflows:
@@ -459,13 +459,13 @@ workflows:
           requires: [deploy-infrastructure]
       - run-migrations:
           requires: [configure-infrastructure]
-      # - deploy-frontend:
-      #     requires: [run-migrations]
-      # - deploy-backend:
-      #     requires: [run-migrations]
-      # - smoke-test:
-      #     requires: [deploy-backend, deploy-frontend]
-      # - cloudfront-update:
-      #     requires: [smoke-test]
-      # - cleanup:
-      #     requires: [cloudfront-update]
+      - deploy-frontend:
+          requires: [run-migrations]
+      - deploy-backend:
+          requires: [run-migrations]
+      - smoke-test:
+          requires: [deploy-backend, deploy-frontend]
+      - cloudfront-update:
+          requires: [smoke-test]
+      - cleanup:
+          requires: [cloudfront-update]
